### ISSUE TITLE
Starter Device variable is ignored

### ISSUE THREAD

**Issue by T2brozz** [cryptic-game/integration-tests#17]
**Describe the bug**
> All device_tests are failing because all tests are not considering the new database variable.

**Reproduce**
>  run the device_tests with the new python backend

**Logs**
> `
Error
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/yannes/Documents/Cryptic/integration-tests/tests/test_device.py", line 230, in test_delete_successful
    actual = self.client.ms("device", ["device", "delete"], device_uuid=device.uuid)
  File "/home/yannes/.local/share/virtualenvs/integration-tests-YiXK7GGM/lib/python3.8/site-packages/PyCrypCli/client.py", line 97, in ms
    raise InvalidServerResponseException(response)
PyCrypCli.exceptions.InvalidServerResponseException: Invalid Server Response: {"data": {"origin": "service", "error": "device_is_starter_device"}, "tag": "90459440-7697-4583-a5d4-5ff1d12355b5"}
`

**Additional Comments**
> Add any other context about the problem here.

**Comment by Defelo** [comment]
fixed in #16
